[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python311"]
cmds = ["python -m pip install --upgrade pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python server.py"
